import { amber, indigo, purple, red } from "@mui/material/colors";
import { SlideProps } from "../hooks/useNavigation";
import { IconName } from "@fortawesome/fontawesome-svg-core";

export const bottomTabs: BottomTabsProps[] = [
  {
    label: "Home",
    value: "home",
    name: "house-heart",
  },
  {
    label: "Explore",
    value: "explore",
    name: "compass",
  },
  {
    label: "Favorite",
    value: "favorite",
    name: "heart",
  },
  {
    label: "Account",
    value: "account",
    name: "user",
  },
];

export const bottomNavItems: SlideProps[] = [
  {
    key: `main_${bottomTabs[0].value}_home`,
    nav: "main",
    stack: bottomTabs[0].value,
    name: "home",
    title: "",
    show: true,
    index: 0,
    id: -1,
    tab: 0,
    slideTo: -1,
    targetUser: null,
  },
  {
    key: `main_${bottomTabs[1].value}_home`,
    nav: "main",
    stack: bottomTabs[1].value,
    name: "home",
    title: "",
    show: true,
    index: 0,
    id: -1,
    tab: 0,
    slideTo: -1,
    targetUser: null,
  },
  {
    key: `main_${bottomTabs[2].value}_home`,
    nav: "main",
    stack: bottomTabs[2].value,
    title: "",
    name: "home",
    show: true,
    index: -1,
    id: -1,
    tab: 0,
    slideTo: -1,
    targetUser: null,
  },
  {
    key: `main_${bottomTabs[3].value}_home`,
    nav: "main",
    stack: bottomTabs[3].value,
    name: "home",
    title: "",
    show: true,
    index: -1,
    id: -1,
    tab: 0,
    slideTo: -1,
    targetUser: null,
  },
];

export type BottomTabsProps = {
  value: string;
  name: IconName;
  label: string;
};

export const exploreTabs = [
  { id: 1, label: "🍽 식단", icon: "utensils-alt" },
  { id: 2, label: "💪 운동", icon: "dumbbell" },
  { id: 3, label: "⭐️ 즐겨찾기", icon: "dumbbell" },
];
//아래 검증 필요
export const groundTabs = [
  { id: 1, label: "운동장" },
  { id: 2, label: "내 기록" },
  { id: 3, label: "인증서" },
  { id: 4, label: "전체 기록" },
  { id: 5, label: "랭킹" },
];
export const userTabs = [
  { id: 1, label: "커뮤니티" },
  { id: 2, label: "인증서" },
];
export const followsTabs = [
  { id: 1, label: "팔로워" },
  { id: 2, label: "팔로잉" },
];
export const storeTabs = [
  { id: 1, label: "교환소" },
  { id: 2, label: "교환내역" },
];
export const searchTabs = [
  { id: 1, label: "유저" },
  { id: 2, label: "챌린지" },
];
export const activityTabs = [
  { id: 1, label: "전체" },
  { id: 2, label: "활동" },
  { id: 3, label: "미션" },
];
export const PUSHER_APP_KEY = "5e3e807338568cf72295";
export const PUSHER_APP_CLUSTER = "ap3";

//공통
export const genderList = [
  { value: "M", emoji: "👨", label: "남자" },
  { value: "W", emoji: "👩", label: "여자" },
];
export const heightList = [
  { value: "-1", label: "신장 선택" },
  { value: "140", label: "140cm" },
  { value: "141", label: "141cm" },
  { value: "142", label: "142cm" },
  { value: "143", label: "143cm" },
  { value: "144", label: "144cm" },
  { value: "145", label: "145cm" },
  { value: "146", label: "146cm" },
  { value: "147", label: "147cm" },
  { value: "148", label: "148cm" },
  { value: "149", label: "149cm" },
  { value: "150", label: "150cm" },
  { value: "151", label: "151cm" },
  { value: "152", label: "152cm" },
  { value: "153", label: "153cm" },
  { value: "154", label: "154cm" },
  { value: "155", label: "155cm" },
  { value: "156", label: "156cm" },
  { value: "157", label: "157cm" },
  { value: "158", label: "158cm" },
  { value: "159", label: "159cm" },
  { value: "160", label: "160cm" },
  { value: "161", label: "161cm" },
  { value: "162", label: "162cm" },
  { value: "163", label: "163cm" },
  { value: "164", label: "164cm" },
  { value: "165", label: "165cm" },
  { value: "166", label: "166cm" },
  { value: "167", label: "167cm" },
  { value: "168", label: "168cm" },
  { value: "169", label: "169cm" },
  { value: "170", label: "170cm" },
  { value: "171", label: "171cm" },
  { value: "172", label: "172cm" },
  { value: "173", label: "173cm" },
  { value: "174", label: "174cm" },
  { value: "175", label: "175cm" },
  { value: "176", label: "176cm" },
  { value: "177", label: "177cm" },
  { value: "178", label: "178cm" },
  { value: "179", label: "179cm" },
  { value: "180", label: "180cm" },
  { value: "181", label: "181cm" },
  { value: "182", label: "182cm" },
  { value: "183", label: "183cm" },
  { value: "184", label: "184cm" },
  { value: "185", label: "185cm" },
  { value: "186", label: "186cm" },
  { value: "187", label: "187cm" },
  { value: "188", label: "188cm" },
  { value: "189", label: "189cm" },
  { value: "190", label: "190cm" },
  { value: "191", label: "191cm" },
  { value: "192", label: "192cm" },
  { value: "193", label: "193cm" },
  { value: "194", label: "194cm" },
  { value: "195", label: "195cm" },
  { value: "196", label: "196cm" },
  { value: "197", label: "197cm" },
  { value: "198", label: "198cm" },
  { value: "199", label: "199cm" },
  { value: "200", label: "200cm" },
];
export const weightList = [
  { value: "-1", label: "체중 선택" },
  { value: "40", label: "40kg" },
  { value: "41", label: "41kg" },
  { value: "42", label: "42kg" },
  { value: "43", label: "43kg" },
  { value: "44", label: "44kg" },
  { value: "45", label: "45kg" },
  { value: "46", label: "46kg" },
  { value: "47", label: "47kg" },
  { value: "48", label: "48kg" },
  { value: "49", label: "49kg" },
  { value: "50", label: "50kg" },
  { value: "51", label: "51kg" },
  { value: "52", label: "52kg" },
  { value: "53", label: "53kg" },
  { value: "54", label: "54kg" },
  { value: "55", label: "55kg" },
  { value: "56", label: "56kg" },
  { value: "57", label: "57kg" },
  { value: "58", label: "58kg" },
  { value: "59", label: "59kg" },
  { value: "60", label: "60kg" },
  { value: "61", label: "61kg" },
  { value: "62", label: "62kg" },
  { value: "63", label: "63kg" },
  { value: "64", label: "64kg" },
  { value: "65", label: "65kg" },
  { value: "66", label: "66kg" },
  { value: "67", label: "67kg" },
  { value: "68", label: "68kg" },
  { value: "69", label: "69kg" },
  { value: "70", label: "70kg" },
  { value: "71", label: "71kg" },
  { value: "72", label: "72kg" },
  { value: "73", label: "73kg" },
  { value: "74", label: "74kg" },
  { value: "75", label: "75kg" },
  { value: "76", label: "76kg" },
  { value: "77", label: "77kg" },
  { value: "78", label: "78kg" },
  { value: "79", label: "79kg" },
  { value: "80", label: "80kg" },
  { value: "81", label: "81kg" },
  { value: "82", label: "82kg" },
  { value: "83", label: "83kg" },
  { value: "84", label: "84kg" },
  { value: "85", label: "85kg" },
  { value: "86", label: "86kg" },
  { value: "87", label: "87kg" },
  { value: "88", label: "88kg" },
  { value: "89", label: "89kg" },
  { value: "90", label: "90kg" },
  { value: "91", label: "91kg" },
  { value: "92", label: "92kg" },
  { value: "93", label: "93kg" },
  { value: "94", label: "94kg" },
  { value: "95", label: "95kg" },
  { value: "96", label: "96kg" },
  { value: "97", label: "97kg" },
  { value: "98", label: "98kg" },
  { value: "99", label: "99kg" },
  { value: "100", label: "100kg" },
  { value: "101", label: "101kg" },
  { value: "102", label: "102kg" },
  { value: "103", label: "103kg" },
  { value: "104", label: "104kg" },
  { value: "105", label: "105kg" },
  { value: "106", label: "106kg" },
  { value: "107", label: "107kg" },
  { value: "108", label: "108kg" },
  { value: "109", label: "109kg" },
  { value: "110", label: "110kg" },
  { value: "111", label: "111kg" },
  { value: "112", label: "112kg" },
  { value: "113", label: "113kg" },
  { value: "114", label: "114kg" },
  { value: "115", label: "115kg" },
  { value: "116", label: "116kg" },
  { value: "117", label: "117kg" },
  { value: "118", label: "118kg" },
  { value: "119", label: "119kg" },
  { value: "120", label: "120kg" },
];
export const goalList = [
  {
    emoji: "👙",
    label: "다이어트",
    value: "다이어트",
  },
  {
    emoji: "💪",
    label: "근육강화",
    value: "근육강화",
  },
  {
    emoji: "🩹",
    label: "재활/치료",
    value: "재활/치료",
  },
  {
    emoji: "💦",
    label: "체력강화",
    value: "체력강화",
  },
];
export const foodFavoriteList = [
  { id: 1, emoji: "🍛", label: "일반식", value: "일반식", checked: false },
  { id: 2, emoji: "🥗", label: "다이어트식", value: "다이어트식", checked: false },
  { id: 3, emoji: "🌱", label: "채식", value: "채식", checked: false },
  { id: 4, emoji: "🥩", label: "육식", value: "육식", checked: false },
];
export const foodAllergyList = [
  { id: 1, label: "계란", value: "계란", checked: false },
  { id: 2, label: "우유", value: "우유", checked: false },
  { id: 3, label: "메밀", value: "메밀", checked: false },
  { id: 4, label: "땅콩", value: "땅콩", checked: false },
  { id: 5, label: "대두", value: "대두", checked: false },
  { id: 6, label: "밀", value: "밀", checked: false },
  { id: 7, label: "고등어", value: "고등어", checked: false },
  { id: 8, label: "게", value: "게", checked: false },
  { id: 9, label: "새우", value: "새우", checked: false },
  { id: 10, label: "돼지고기", value: "돼지고기", checked: false },
  { id: 11, label: "복숭아", value: "복숭아", checked: false },
  { id: 12, label: "토마토", value: "토마토", checked: false },
  { id: 13, label: "아황산류", value: "아황산류", checked: false },
  { id: 14, label: "호두", value: "호두", checked: false },
  { id: 15, label: "닭고기", value: "닭고기", checked: false },
  { id: 16, label: "쇠고기", value: "쇠고기", checked: false },
  { id: 17, label: "오징어", value: "오징어", checked: false },
  { id: 18, label: "조개", value: "조개", checked: false },
  { id: 19, label: "홍합", value: "홍합", checked: false },
  { id: 20, label: "전복", value: "전복", checked: false },
  { id: 21, label: "굴", value: "굴", checked: false },
];
export const workoutFavoriteList = [
  { id: 1, label: "스트레칭", value: "스트레칭", checked: false },
  { id: 2, label: "맨몸 피트니스", value: "맨몸 피트니스", checked: false },
  { id: 3, label: "웨이트 트레이닝", value: "웨이트 트레이닝", checked: false },
  { id: 4, label: "홈 웨이트 트레이닝", value: "홈 웨이트 트레이닝", checked: false },
  { id: 5, label: "크로스핏", value: "크로스핏", checked: false },
  { id: 6, label: "필라테스", value: "필라테스", checked: false },
  { id: 7, label: "홈 필라테스", value: "홈 필라테스", checked: false },
  { id: 8, label: "요가", value: "요가", checked: false },
  { id: 9, label: "홈 요가", value: "홈 요가", checked: false },
  { id: 10, label: "복싱", value: "복싱", checked: false },
  { id: 11, label: "홈 복싱", value: "홈 복싱", checked: false },
  { id: 12, label: "댄스", value: "댄스", checked: false },
  { id: 13, label: "걷기 (느린 속도, 3km/h)", value: "걷기 (느린 속도, 3km/h)", checked: false },
  { id: 14, label: "걷기 (빠른 속도, 4km/h)", value: "걷기 (빠른 속도, 4km/h)", checked: false },
  { id: 15, label: "러닝 (느린 속도, 5km/h)", value: "러닝 (느린 속도, 5km/h)", checked: false },
  { id: 16, label: "러닝 (중간 속도, 8km/h)", value: "러닝 (중간 속도, 8km/h)", checked: false },
  { id: 17, label: "러닝 (빠른 속도, 10km/h)", value: "러닝 (빠른 속도, 10km/h)", checked: false },
  { id: 18, label: "타바타/서킷트레이닝", value: "타바타/서킷트레이닝", checked: false },
  { id: 19, label: "사이클", value: "사이클", checked: false },
  { id: 20, label: "실내 사이클", value: "실내 사이클", checked: false },
  { id: 21, label: "클라이밍", value: "클라이밍", checked: false },
  { id: 22, label: "골프", value: "골프", checked: false },
  { id: 23, label: "등산", value: "등산", checked: false },
  { id: 24, label: "수영", value: "수영", checked: false },
  { id: 25, label: "볼링", value: "볼링", checked: false },
  { id: 26, label: "탁구", value: "탁구", checked: false },
  { id: 27, label: "배구", value: "배구", checked: false },
  { id: 28, label: "축구", value: "축구", checked: false },
  { id: 29, label: "농구", value: "농구", checked: false },
  { id: 30, label: "당구", value: "당구", checked: false },
  { id: 31, label: "승마", value: "승마", checked: false },
  { id: 32, label: "테니스", value: "테니스", checked: false },
  { id: 33, label: "줄넘기", value: "줄넘기", checked: false },
  { id: 34, label: "스쿼시", value: "스쿼시", checked: false },
  { id: 35, label: "훌라후프", value: "훌라후프", checked: false },
  { id: 36, label: "기타 운동", value: "기타 운동", checked: false },
];
export const workoutWeekList = [
  { id: 1, value: "월", label: "월", checked: false },
  { id: 2, value: "화", label: "화", checked: false },
  { id: 3, value: "수", label: "수", checked: false },
  { id: 4, value: "목", label: "목", checked: false },
  { id: 5, value: "금", label: "금", checked: false },
  { id: 6, value: "토", label: "토", checked: false },
  { id: 7, value: "일", label: "일", checked: false },
];
export const bodyActivityList = [
  { id: 1, emoji: "🪑", label: "주로 앉아있어요", desc: "하루 평균 걸음수 3,000보 이하", value: "1", checked: false },
  { id: 2, emoji: "🧘", label: "일주일에 1~2일 운동을 해요", desc: "하루 평균 걸음수 3,000보 ~ 8,000보", value: "2", checked: false },
  { id: 3, emoji: "🧍‍♀️", label: "일주일에 3~5일 운동을 해요", desc: "하루 평균 걸음수 8,000보 ~ 10,000보", value: "3", checked: false },
  { id: 4, emoji: "🚶‍♀️", label: "일주일에 6~7일 운동을 해요", desc: "하루 평균 걸음수 10,000보 ~ 12,000보", value: "4", checked: false },
  { id: 5, emoji: "🏃‍♀️", label: "하루에 두번씩 운동을 해요", desc: "하루 평균 걸음수 12,000보 이상", value: "5", checked: false },
];
export const injuryBodypartList = [
  { id: 1, value: "팔", label: "팔=", checked: false },
  { id: 2, value: "다리", label: "다리", checked: false },
];
export const foodDbList = [
  {
    id: 1,
    title: "닭가슴살",
    desc: "닭가슴살 | 100g",
    kcal: 109,
  },
  {
    id: 2,
    title: "닭가슴살",
    desc: "닭가슴살 | 100g",
    kcal: 109,
  },
  {
    id: 3,
    title: "닭가슴살",
    desc: "닭가슴살 | 100g",
    kcal: 109,
  },
  {
    title: "닭가슴살",
    desc: "닭가슴살 | 100g",
    kcal: 109,
  },
  {
    id: 4,
    title: "닭가슴살",
    desc: "닭가슴살 | 100g",
    kcal: 109,
  },
];
