export type ShorcutProps = {
  keyword: string;
  type: string;
};
export type SearchUserProps = {
  area: string;
  follower: number;
  gender: string;
  id: number;
  is_following: number;
  nickname: string;
  profile: string;
  together_following: number;
};
export type SearchMissionProps = {
  bookmarks: number;
  comments: number;
  description: string;
  ended_at: string | null;
  event_type: string | null;
  feeds_count: number;
  id: number;
  is_available: number;
  is_bookmark: number;
  is_ended: number | null;
  is_event: boolean;
  is_ground: number;
  is_ocr: number;
  is_old_event: number;
  is_reserve_available: number;
  is_reserve_before: any | null;
  mission_stat_id: number | null;
  mission_stat_user_id: number | null;
  outside_product_id: number | null;
  owner: SearchUserProps[];
  owner_area: string | null;
  owner_followers: number;
  owner_gender: string;
  owner_id: number;
  owner_is_following: number;
  owner_nickname: string;
  owner_profile: string;
  place_address: string | null;
  place_description: string | null;
  place_image: string | null;
  place_title: string | null;
  place_url: string | null;
  product_brand: string | null;
  product_id: number | null;
  product_image: string | null;
  product_price: number | null;
  product_title: string | null;
  product_type: string | null;
  product_url: string | null;
  started_at: string | null;
  success_count: number;
  thumbnail_image: string;
  title: string;
};
